### ISSUE TITLE
Add package with functions for the Passphrase Generator

### ISSUE THREAD

**Issue by tredoe** [bkeroack/wordentropy2#1]
If the necessary functions for the Passphrase Generator were into a package, then it could be used from external apps.

**Comment by bkeroackdsc** [comment]
Interesting idea. If it were a package it may make sense to allow configurable word corpora as well, but the application is hard-coded to assume the POS structure. That would require more engineering.

**Comment by bkeroack** [comment]
@kless Done. See https://github.com/bkeroack/libwordentropy

**Comment by tredoe** [comment]
Awesome! Thank you very much.
