### ISSUE TITLE
Error opening plot URL file

### ISSUE THREAD

**Issue by egon010** [bkeroack/wordentropy2#5]
Upon build, complains of missing file:
Error opening plot URL file: open data/plot_urls.txt: no such file or directory

Creating the file, blank results in:
Malformed plot URL file:

In both cases, running with: ./wordentropy2 -local=true

What's the format of the plot_urls.txt file? Should the local flag turn off calling get_plots()?

**Comment by bkeroack** [comment]
Yup, that was a bug. 

plot_urls.txt is where the Python script that generates Plotly plots puts the hosted URLs. The go code reads that and inserts them into the view templates.
